version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
  
  postgress:
    container_name: postgres-data
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: a123
      POSTGRES_DB: data
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


